### PR TITLE
WIP Firewalld playbook added - tested on CentOS8 stable/ussuri deployment

### PR DESCRIPTION
**Pull request by bbezak**

### CODE REVIEW

**Comment by bbezak** [comment]
needs https://github.com/michaelrigart/ansible-role-interfaces/pull/92 and https://review.opendev.org/#/c/763180/ to be merged first

**Review by oneswig — COMMENTED** [review]
Approach looks good to me but someone else with experience with applying firewall rules should review.

**Comment by oneswig** [comment]
@bbezak are there updates to apply to this?

**Comment by cityofships** [comment]
This playbook has been applied during Wireguard deployment and it works fine. Would be cool to convert it to a role though.

**Pull request closed without merging**
